gg.jte.development-mode=true
gg.jte.templateLocation=src/main/frontend/views
spring.application.name=demo
spring.web.resources.static-locations=file:src/main/resources/static/,file:src/main/resources/vite/,classpath:/static/,classpath:/vite/